# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded CachedRmdb 1.0 [list source [file join $dir rmdb.tc_]]
package ifneeded RmdbGraph 1.0 [list source [file join $dir rmgraph.tc_]]
package ifneeded RmdbQueue 1.0 [list source [file join $dir rmqueue.tc_]]
package ifneeded RmdbTree 1.0 [list source [file join $dir rmtree.tc_]]
package ifneeded RmdbWalker 1.0 [list source [file join $dir rmwalker.tc_]]
package ifneeded RunManager 1.0 [list source [file join $dir runmgr.tc_]]
package ifneeded RunManagerUser 1.0 [list source [file join $dir rmuser.tc_]]
package ifneeded RunManagerUtil 1.0 [list source [file join $dir rmutil.tc_]]
