#!/bin/sh
# ----------------------------------------------------------------------
#  DEMO: mtilabel in mtiwidgets
# ----------------------------------------------------------------------
#\
exec itkwish "$0" ${1+"$@"}
package require Mtiwidgets

# itkwish interprets the rest...
# ----------------------------------------------------------------------
. configure -background white

mtiwidgets::mtilabel .lw -borderwidth 4 -relief sunken
pack .lw -padx 4 -pady 4
.lw configure -text "Warning message" -labelforeground red -labelbackground yellow


iwidgets::optionmenu .pos -labeltext "Message:" -command {
    switch [.pos get] {
		Note {
			.lw configure -text "Note message" -labelforeground black -labelbackground white
		}
		Warning {
			.lw configure -text "Warning message" -labelforeground red -labelbackground yellow
		}
		Error {
			.lw configure -text "Error message" -labelforeground yellow -labelbackground orange
		}
		Fatal {
			.lw configure -text "Fatal message" -labelforeground black -labelbackground red
		}
	}
}
pack .pos -padx 4 -pady 4

.pos insert end Note Warning Error Fatal
.pos select Warning
