
##  en.msg

namespace import -force ::msgcat::mcset

mcset en EditorTitle            "HDS Text Editor"
mcset en Usage                   "Usage: hte.tcl \[filename\] \[-syntax vdhl|verilog|tcl\] \[-line n\]"
mcset en InvalidSyntax          "Invalid syntax mode:"
mcset en InvalidLineNumber       "Invalid line number:"
mcset en Ignored                "ignored"
mcset en AboutTitle             "About HTE"
mcset en UsedPackages           "Used packages:\n"

mcset en VHDLFiles              "VHDL-Files "
mcset en VerilogFiles           "Verilog-Files "
mcset en TclFiles               "Tcl-Files "
mcset en AllFiles               "All-Files "

mcset en OpenDlgTitle           "Open File"
mcset en WriteProtWhenOpen      "File is write protected!\nOpen file as read only!"
mcset en PermissionDenied       "Permission denied!"
mcset en Untitled               "Untitled"
mcset en WriteProtWhenSave      "is write protected!\nUse SAVE AS.. instead!"
mcset en SaveDlgTitle           "Save File"
mcset en NoWritePerm            "No write permission!"
mcset en CannotSave             "Can´t save file "
mcset en MaybeNoWritePerm       "\nMaybe no write permission!"
mcset en WordFile               "File "
mcset en HasChangedSaveIt       " has changed!\n Save it ?"
mcset en QuestionTitle          "Question"

mcset en EnterLineNumber        "Please enter line number"
mcset en GotoLine               "Goto Line"

mcset en LineOutOfRange         "Line number out of range!"
mcset en WarningTitle           "Warning"

mcset en FileMenuTxt            "\"&File\""

mcset en NewItemTxt             "\"&New\""
mcset en NewItemDesc            "\"New Text\""
mcset en OpenItemTxt            "\"&Open\""
mcset en OpenItemDesc           "\"Open File\""
mcset en SaveItemTxt            "\"&Save\""
mcset en SaveItemDesc           "\"Save active File\""
mcset en SaveAsItemTxt          "\"Save &as ...\""
mcset en SaveAsItemDesc         "\"Save active File as ..\""
mcset en CloseItemTxt           "\"&Close\""
mcset en CloseItemDesc          "\"Close active File\""
mcset en PrintItemTxt    "\"&Print...\""
mcset en PrintItemDesc    "\"Print current file\""
mcset en PageItemTxt    "\"Page Setup...\""
mcset en PageItemDesc    "\"Page setup\""
mcset en RecentFilesItemTxt     "\"Recent file list\""
mcset en ExitItemTxt            "\"E&xit\""
mcset en ExitItemDesc           "\"Exit editor\""

mcset en EditMenuTxt            "\"&Edit\""

mcset en CopyItemTxt            "\"Copy\""
mcset en CopyItemDesc           "\"Copy to Clipboard\""
mcset en CutItemTxt             "\"Cut\""
mcset en CutItemDesc            "\"Cut to Clipboard\""
mcset en PasteItemTxt           "\"Paste\""
mcset en PasteItemDesc          "\"Paste from Clipboard\""
mcset en SelectAllItemTxt       "\"Select all\""
mcset en SelectAllItemDesc      "\"Select All\""
mcset en GotoLineItemTxt        "\"Goto Line ...\""
mcset en GotoLineItemDesc       "\"Goto Line\""
mcset en SearchItemTxt          "\"Search ...\""
mcset en SearchItemDesc         "\"Search dialog\""
mcset en SearchInFilesItemTxt   "\"Search in files ...\""               
mcset en SearchInFilesItemDesc  "\"Search in files\""
mcset en ReplaceItemTxt         "\"Replace ...\""
mcset en ReplaceItemDesc        "\"Replace dialog\""
mcset en UndoItemTxt            "\"Undo\""
mcset en UndoItemDesc           "\"Undo\""
mcset en RedoItemTxt            "\"Redo\""      
mcset en RedoItemDesc           "\"Redo\""

mcset en HelpMenuTxt            "\"&Help\""

mcset en AboutItemTxt           "\"About\""
mcset en AboutItemDesc          "\"About\"" 

mcset en BallonNew              "Create a new file"
mcset en BallonOpen             "Open an existing file"
mcset en BallonSave             "Save file"
mcset en BallonClose            "Close File"
mcset en BallonPrint		"Print file"

mcset en BallonCut              "Cut selection"
mcset en BallonCopy             "Copy selection"
mcset en BallonPaste            "Paste selection"

mcset en BallonUndo             "Undo"
mcset en BallonRedo             "Redo"

mcset en BallonFind             "Find Dialog"
mcset en BallonReplace          "Replace Dialog"

mcset en BallonExit             "Exit editor"

# Search dialog messages
mcset en SearchString           "Search string"
mcset en NotFound               "not found!"
mcset en OptionsTitle           "Options"
mcset en DefaultOpt             "Default options"
mcset en IgnoreCase             "ignore case"
mcset en PromptReplace          "prompt before replace"
mcset en SearchArea             " Area : "
mcset en Forward                "Forward"
mcset en Backward               "Backward"
mcset en Global                 "Global"
mcset en SearchMatch            " Match : "
mcset en Exact                  "exact"
mcset en Regexp                 "regexp"
mcset en SearchBlink            " Blink : "
mcset en DuringSearch           "during search"
mcset en BlinkOff               "off"
mcset en BlinkAlways            "always"
mcset en SearchTitle            "Search "
mcset en EnterSearchString      " Enter search string: "

# Replace dialog messages
mcset en yesName                "Yes"
mcset en noName                 "No"
mcset en cancelName             "Cancel"
mcset en ReplaceOccurrence      " Replace this occurrence ? "
mcset en ReplaceQuestion        " Replace  ? "
mcset en ReplaceTitle           "Replace "
mcset en SearchForString        " Search for string: "
mcset en ReplaceWithString      " Replace with string: "

# Status bar indicators
mcset en FileMode               "Mode"
mcset en FileLine               "Line"

# end of en.msg


