
## ru.msg

namespace import -force ::msgcat::mcset

mcset ru EditorTitle            "HDS Text Editor"

mcset ru VHDLFiles              "Ê¡ ÃŸ-VHDL {*.vhd *.vhdl}"
mcset ru VerilogFiles           "Ê¡ ÃŸ-Verilog {*.v *.vlog}"
mcset ru TclFiles               "Ê¡ ÃŸ-Tcl {*.tcl *.tk *.itcl *.itk}"
mcset ru AllFiles               "˜”≈-∆¡ ÃŸ {*.* *}"

mcset ru OpenDlgTitle           "Open File"
mcset ru WriteProtWhenOpen      "File is write protected!\nOpen file as read only!"
mcset ru PermissionDenied       "Permission denied!"
mcset ru Untitled               "Untitled"
mcset ru WriteProtWhenSave      "is write protected!\nUse SAVE AS.. instead!"
mcset ru SaveDlgTitle           "Save File"
mcset ru NoWritePerm            "No write permission!"
mcset ru CannotSave             "Can¥t save file "
mcset ru MaybeNoWritePerm       "\nMaybe no write permission!"
mcset ru WordFile               "File "
mcset ru HasChangedSaveIt       " has changed!\n Save it ?"
mcset ru QuestionTitle          "Question"

mcset ru EnterLineNumber        "Please enter line number"
mcset ru GotoLine               "Goto Line"

mcset ru LineOutOfRange         "Line number out of range!"
mcset ru WarningTitle           "Warning"

mcset ru FileMenuTxt            "\"&Ê¡ Ã\""

mcset ru NewItemTxt             "\"&New\""
mcset ru NewItemDesc            "\"New Text\""
mcset ru OpenItemTxt            "\"&Open\""
mcset ru OpenItemDesc           "\"Open File\""
mcset ru SaveItemTxt            "\"&Save\""
mcset ru SaveItemDesc           "\"Save active File\""
mcset ru SaveAsItemTxt          "\"Save &as ...\""
mcset ru SaveAsItemDesc         "\"Save active File as ..\""
mcset ru CloseItemTxt           "\"&Close\""
mcset ru CloseItemDesc          "\"Close active File\""
mcset ru ExitItemTxt            "\"E&xit\""
mcset ru ExitItemDesc           "\"Exit editor\""

mcset ru EditMenuTxt            "\"&Edit\""

mcset ru CopyItemTxt            "\"Copy\""
mcset ru CopyItemDesc           "\"Copy to Clipboard\""
mcset ru CutItemTxt             "\"Cut\""
mcset ru CutItemDesc            "\"Cut to Clipboard\""
mcset ru PasteItemTxt           "\"Paste\""
mcset ru PasteItemDesc          "\"Paste from Clipboard\""
mcset ru SelectAllItemTxt       "\"Select all\""
mcset ru SelectAllItemDesc      "\"Select All\""
mcset ru GotoLineItemTxt        "\"Goto Line ...\""
mcset ru GotoLineItemDesc       "\"Goto Line\""
mcset ru SearchItemTxt          "\"Search ...\""
mcset ru SearchItemDesc         "\"Search dialog\""
mcset ru SearchInFilesItemTxt   "\"Search in files ...\""               
mcset ru SearchInFilesItemDesc  "\"Search in files\""
mcset ru ReplaceItemTxt         "\"Replace ...\""
mcset ru ReplaceItemDesc        "\"Replace dialog\""
mcset ru UndoItemTxt            "\"Undo\""
mcset ru UndoItemDesc           "\"Undo\""
mcset ru RedoItemTxt            "\"Redo\""      
mcset ru RedoItemDesc           "\"Redo\""

mcset en HelpMenuTxt            "\"&Help\""

mcset en AboutItemTxt           "\"About\""
mcset en AboutItemDesc          "\"About\"" 

mcset ru BallonNew              "Create a new file"
mcset ru BallonOpen             "Open an existing file"
mcset ru BallonSave             "Save file"
mcset ru BallonClose            "Close File"

mcset ru BallonCut              "Cut selection"
mcset ru BallonCopy             "Copy selection"
mcset ru BallonPaste            "Paste selection"

mcset ru BallonUndo             "Undo"
mcset ru BallonRedo             "Redo"

mcset ru BallonFind             "Find Dialog"
mcset ru BallonReplace          "Replace Dialog"

mcset ru BallonExit             "Exit editor"

# end of ru.msg


