#! /bin/csh -f
#
#Copyright 1991-2009 Mentor Graphics Corporation
#
#All Rights Reserved.
#
#THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY INFORMATION WHICH IS THE PROPERTY 
#OF MENTOR GRAPHICS CORPORATION OR ITS LICENSORS AND IS SUBJECT TO LICENSE TERMS.
#   

if ($#argv == 1) then
	set alt_lic_file_path = $argv[1]
	if ( ! -r $alt_lic_file_path ) then
		echo "ERROR: Cannot find license file: $alt_lic_file_path "
		exit 1
	endif
endif

set DAEMON = unknown
set PLATFORM = unknown
set grep_mti_status = 1
set grep_mgc_status = 1
# channels all vco determination into vco script
# server script assumes to be in modeltech/<platform>/START_SERVER
# vco script assumes to be in modeltech/vco
set server_script_dir = `dirname $0`
set PLATFORM = `$server_script_dir/../vco`
# set uname = `uname`
# set utype = `uname -r`
# set vco = ${uname}${utype}
# switch ($vco)
# 	case SunOS4*:
# 		set PLATFORM = sun4
# 		breaksw
# 	case SunOS5*:
# 		switch ($utype)
# 			case 5.7*:
# 				if ( -x /bin/isainfo ) then
#                     			switch (`/bin/isainfo -n`)
#                         			case sparcv9*:
#                             				set PLATFORM  = sunos5v9
# 							breaksw
#                         			default:
#                             				set PLATFORM  = sunos5
#                             				breaksw
#                     			endsw
#                 		else
#                     			set PLATFORM = sunos5
#                 		endif
# 				breaksw
# 			case 5.5.1*:
# 					set PLATFORM = sunos5_251
# 					breaksw
# 			case 5.6*:
# 					set PLATFORM = sunos5
# 					breaksw
# 					
# 		endsw
# 		breaksw
# 	case AIX*:
# 		set PLATFORM = rs6000
# 		breaksw
# 	case "HP-UX*B.11.*":
#                 if ( `getconf KERNEL_BITS` == 64 ) then
#                     set PLATFORM = hppa64
#                 else
#                     set PLATFORM = hp700
#                 endif
#                 breaksw
# 	case HP-UX*:
# 		set PLATFORM = hp700
# 		breaksw
# 	case Linux*:
# 		set PLATFORM = linux
# 		breaksw
# endsw

if ( $PLATFORM == unknown ) then
	echo "START_SERVER doesn't recognize this hardware/OS combination."
	exit 1
endif


if (-d $PLATFORM) cd $PLATFORM

if ($?alt_lic_file_path) then
	set LICENSE_FILE = $alt_lic_file_path
else if ( -r ../license.dat) then
	set LICENSE_FILE = ../license.dat
else if ( -r ./license.dat) then
	set LICENSE_FILE = ./license.dat
else
	set LICENSE_FILE = ../license.dat
endif


if ( -r $LICENSE_FILE) then

	grep DAEMON $LICENSE_FILE | grep ' modeltech ' > /dev/null
	if ($status == 0) then
		set DAEMON = modeltech
	else
		grep DAEMON $LICENSE_FILE | grep ' mgcld ' > /dev/null
		if ($status == 0) then
			set DAEMON = mgcld
		endif
	endif
	
	if ($DAEMON == unknown) then
		echo "License file: $LICENSE_FILE doesn't require a server"
		exit 0
	endif

	grep 'SERVER.*hostname' $LICENSE_FILE > /dev/null
	if ($status == 0) then
		echo "Edit this line in the file ${LICENSE_FILE}:"
		echo ""
		echo -n "   "
		grep 'SERVER.*hostname' $LICENSE_FILE
		echo ""
		echo "Replace 'hostname' with the actual hostname of the server"
		echo "Then run this script again."
		exit 2
	endif

	switch ( $PLATFORM )
		case sun4:
			ps -acx | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case sunos5:
			/usr/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case sunos5_251:
			/usr/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case sunos5v9:
			/usr/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case hp700:
			/usr/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case hp700_1020:
			/usr/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case hppa64:
			/usr/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case rs6000:
			/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case rs64:
			/bin/ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
		case linux:
			/bin/ps -dea | grep ' mgcld$' > /dev/null
			set grep_mgc_status = $status
			if ($grep_mgc_status == 0) then
				echo "The mgcld license daemon is already running."
				./lmstat -c $LICENSE_FILE -i
				exit 3
			endif
			breaksw
		case linux_rh60:
			/bin/ps -dea | grep ' mgcld$' > /dev/null
			set grep_mgc_status = $status
			if ($grep_mgc_status == 0) then
				echo "The mgcld license daemon is already running."
				./lmstat -c $LICENSE_FILE -i
				exit 3
			endif
			breaksw
		default:
			ps -dea | grep $DAEMON > /dev/null
			set grep_mti_status = $status
			breaksw
	endsw

	if ($grep_mti_status == 0) then
		echo "The $DAEMON license daemon is already running."
		./lmstat -c $LICENSE_FILE -i
		exit 3
	endif



	if (-e /usr/tmp/lockmodeltech && $DAEMON == modeltech) then
		echo "Please delete the lock file at /usr/tmp/lockmodeltech."
		echo "Then run this script again."
		exit 4
	endif

	if (-e /usr/tmp/lockmgcld && $DAEMON == mgcld) then
		echo "Please delete the lock file at /usr/tmp/lockmgcld."
		echo "Then run this script again."
		exit 4
	endif

	if ($DAEMON == modeltech) then
		set LOGFILE = /usr/tmp/modeltech_lm.log
	else if ($DAEMON == mgcld) then
		set LOGFILE = /usr/tmp/mgcld_lm.log
	endif
	if (-e $LOGFILE) mv -f $LOGFILE $LOGFILE.bak

	./lmgrd -c $LICENSE_FILE > $LOGFILE &
	if ($status == 0) then
		echo "Waiting for license manager to start"
		if ($DAEMON == modeltech) then
			tail -f $LOGFILE | awk '{ print $0 } /modeltech/ { printf("Hit Control-C to continue.\n"); exit 0 }'
		else if ($DAEMON == mgcld) then
			tail -f $LOGFILE | awk '{ print $0 } /mgcld/ { printf("Hit Control-C to continue.\n"); exit 0 }'
		endif
	endif
else
	echo "ERROR: Cannot find license file: $LICENSE_FILE "
	echo "       Please contact your distributor or Model Technology"
	exit 5
endif
